name: quiz_assigment
description: "Quiz app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.4

dependencies:
  animated_splash_screen: 1.3.0
  drift: 2.22.1
  drift_flutter: 0.2.2
  sqlite3_flutter_libs: 0.5.24
  # path_provider: 2.0.0
  # path: 1.8.3
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_svg: 2.0.16
  readmore: 3.0.0
  remixicon: 1.3.0
  riverpod_annotation: 2.6.1
  retrofit: 4.4.0
  logger: 2.4.0  # for logging purpose
  json_annotation: 4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  riverpod_generator: 2.6.3
  build_runner: 2.4.13
  custom_lint: 0.7.0
  riverpod_lint: 2.6.3
  drift_dev: 2.22.1
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  json_serializable: 6.8.0
  freezed: ^2.5.7

flutter:
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Regular.otf
        - asset: fonts/Satoshi-Italic.otf
          style: italic
  uses-material-design: true
  assets:
    - assets/svg/newspaper-svgrepo-com.svg
    - assets/images/logo.png
    - assets/images/news.jpg
  
  
